// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password) 
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, created_at, updated_at, email, hashed_password, chirpy_red
`

type CreateUserParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.ChirpyRed,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec

DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getPass = `-- name: GetPass :one

SELECT id, created_at, updated_at, email, hashed_password, chirpy_red FROM users 
where email = $1
`

func (q *Queries) GetPass(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getPass, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.ChirpyRed,
	)
	return i, err
}

const updatePass = `-- name: UpdatePass :one
UPDATE users
  SET hashed_password = $1, email = $2, updated_at = $3
  WHERE id = $4
RETURNING id, created_at, updated_at, email, hashed_password, chirpy_red
`

type UpdatePassParams struct {
	HashedPassword string
	Email          string
	UpdatedAt      time.Time
	ID             uuid.UUID
}

func (q *Queries) UpdatePass(ctx context.Context, arg UpdatePassParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePass,
		arg.HashedPassword,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.ChirpyRed,
	)
	return i, err
}

const upgradeChirpy = `-- name: UpgradeChirpy :one
UPDATE users
SET chirpy_red = $1 
where id = $2
RETURNING id, created_at, updated_at, email, hashed_password, chirpy_red
`

type UpgradeChirpyParams struct {
	ChirpyRed bool
	ID        uuid.UUID
}

func (q *Queries) UpgradeChirpy(ctx context.Context, arg UpgradeChirpyParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upgradeChirpy, arg.ChirpyRed, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.ChirpyRed,
	)
	return i, err
}
